DROP DATABASE IF EXISTS blog_mvc;
CREATE DATABASE IF NOT EXISTS blog_mvc;
USE blog_mvc;
DROP TABLE IF EXISTS T_POST;
DROP TABLE IF EXISTS T_COMMENT;




CREATE TABLE T_POST (
	POST_ID int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	POST_DATE datetime NOT NULL,
	POST_TITLE varchar(255) NOT NULL,
	POST_CONTENT varchar(255) NOT NULL
) ENGINE=INNODB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE T_COMM (
	COMMENT_ID int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	COMMENT_DATE datetime NOT NULL,
	COMMENT_AUTHOR varchar(255) NOT NULL,
	COMMENT_CONTENT varchar(255) NOT NULL,
	POST_ID INTEGER NOT NULL,
	FOREIGN KEY (POST_ID) REFERENCES T_POST (POST_ID)
) ENGINE=INNODB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;


insert into T_POST(POST_DATE, POST_TITLE, POST_CONTENT) values
(NOW(), 'Premier billet', 'Bonjour monde ! Ceci est le premier billet sur mon blog.');
insert into T_POST(POST_DATE, POST_TITLE, POST_CONTENT) values
(NOW(), 'Au travail', 'Il faut enrichir ce blog dès maintenant.');

insert into T_COMM(COMMENT_DATE, COMMENT_AUTHOR, COMMENT_CONTENT, POST_ID) values
(NOW(), 'A. Nonyme', 'Bravo pour ce début', 1);
insert into T_COMM(COMMENT_DATE, COMMENT_AUTHOR, COMMENT_CONTENT, POST_ID) values
(NOW(), 'Moi', 'Merci ! Je vais continuer sur ma lancée', 1);


